### ISSUE TITLE
スペクトログラムの軸の単位

### ISSUE THREAD

**Issue by koda-saki** [tky823/audio_source_separation#75]
NMFなどを実行して出力されるスペクトログラムの縦軸と横軸の単位は何でしょうか？

**Comment by tky823** [comment]
入力に依存します．

例えば，以下のコードではサンプリング周波数が8000kHzの信号を256サンプルごろにずらしながら分析しています．
この場合，横軸（時間軸）の1メモリは0.032秒（=256/8000）で，縦軸（周波数軸）の1メモリは，7.8125Hz（=4000/512）です
https://colab.research.google.com/github/tky823/audio_source_separation/blob/main/egs/nmf-example/euc-nmf/test_euc-nmf.ipynb

上記のコードであれば
```python
_, _, spectrogram = ss.stft(x, nperseg=fft_size, noverlap=fft_size-hop_size)
```
の部分を
```python
freqs, times, spectrogram = ss.stft(x, nperseg=fft_size, noverlap=fft_size-hop_size)
```
とし，`freqs * 8000`と`times / 8000`とすれば，実際の各メモリの値が計算できます．

**Comment by koda-saki** [comment]
迅速かつ丁寧に解説していただきありがとうございます。

こちらのミスで、返信が遅れてしまい申し訳ございませんでした。
