### ISSUE TITLE
test_euc-cnmf_ja.ipynbの再構成信号とNMF後の各信号に関するプログラムについて

### ISSUE THREAD

**Issue by koda-saki** [tky823/audio_source_separation#76]
test_euc-cnmf_ja.ipynbの再構成信号とNMF後の各信号に関するプログラムについての質問です。

basisには基底行列(分離後の各音の周波数)が、activationには係数行列(分離した各音の音量の時間変化)が格納されているという理解で間違い無いでしょうか？

また、euc-cnmf.pyにphaseは何を表していますでしょうか？

質問箇所のソースコード(test_euc-cnmf_ja.ipynb)

再構成信号
```
Z = basis[:, :, np.newaxis] * activation[np.newaxis, :, :] * phase
Z = np.sum(Z, axis=1)
_, z = ss.istft(Z, nperseg=fft_size, noverlap=fft_size-hop_size)
z = z / np.abs(z).max()
ipd.Audio(z, rate=sr)
```
NMF後の各信号
```
for idx in range(n_basis):
    Z = basis[:, idx: idx+1] * activation[idx: idx+1, :] * phase[:, idx, :]
    _, z = ss.istft(Z, nperseg=fft_size, noverlap=fft_size-hop_size)
    z = z / np.abs(z).max()
    display(ipd.Audio(z, rate=sr))

for idx in range(n_basis):
    estimated_spectrogram = basis[:, idx: idx + 1] * activation[idx: idx + 1, :] * phase[:, idx, :]

    estimated_power = np.abs(estimated_spectrogram)**2
    estimated_power[estimated_power < 1e-12] = 1e-12
    log_spectrogram = 10 * np.log10(estimated_power)

    plt.figure()
    plt.pcolormesh(log_spectrogram, cmap='jet')
    plt.show()
```

**Comment by tky823** [comment]
> basisには基底行列(分離後の各音の周波数)が、activationには係数行列(分離した各音の音量の時間変化)が格納されているという理解で間違い無いでしょうか？

basisが基底行列，activationが係数行列はその通りです．上記の手法（[複素NMF](https://www.kecl.ntt.co.jp/people/kameoka.hirokazu/publications/Kameoka2009ICASSP04-complexNMF.pdf)）は，複素スペクトログラムを低ランクに近似するための最適化手法であり，音がきちんと分離できているかは保証されませんが．

> euc-cnmf.pyにphaseは何を表していますでしょうか？

位相です．位相がわからない場合は，[短時間フーリエ変換の基礎と応用](https://www.jstage.jst.go.jp/article/jasj/72/12/72_764/_pdf)の2.3節などをご覧ください．

**Comment by koda-saki** [comment]
この度は、再構成信号のプログラムについて、早急にご返信いただき誠にありがとうございます。

お忙しいなか、ご丁寧に対応いただき感謝いたします。
